import type { RequestHandler } from 'express';
import { createAddressSchema, addressIdSchema, customerPreferencesSchema, customerProfileSchema, tailorProfileSchema, tailorVerificationSchema, updateAddressSchema } from '../validators/profile.schemas.js';
import { createAddress, deleteAddress, getCustomerProfile, getTailorProfile, listAddresses, submitTailorVerification, updateAddress, updateCustomerPreferences, updateCustomerProfile, updateTailorProfile } from '../services/profile.service.js';

export const readCustomerProfile: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: await getCustomerProfile(request.auth!.userId) }); } catch (error) { next(error); } };
export const patchCustomerProfile: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: { profile: await updateCustomerProfile(request.auth!.userId, customerProfileSchema.parse(request.body)) } }); } catch (error) { next(error); } };
export const patchCustomerPreferences: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: { preferences: await updateCustomerPreferences(request.auth!.userId, customerPreferencesSchema.parse(request.body)) } }); } catch (error) { next(error); } };
export const readAddresses: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: { addresses: await listAddresses(request.auth!.userId) } }); } catch (error) { next(error); } };
export const addAddress: RequestHandler = async (request, response, next) => { try { response.status(201).json({ success: true, data: { address: await createAddress(request.auth!.userId, createAddressSchema.parse(request.body)) } }); } catch (error) { next(error); } };
export const patchAddress: RequestHandler = async (request, response, next) => { try { const { addressId } = addressIdSchema.parse(request.params); response.json({ success: true, data: { address: await updateAddress(request.auth!.userId, addressId, updateAddressSchema.parse(request.body)) } }); } catch (error) { next(error); } };
export const removeAddress: RequestHandler = async (request, response, next) => { try { const { addressId } = addressIdSchema.parse(request.params); await deleteAddress(request.auth!.userId, addressId); response.status(204).send(); } catch (error) { next(error); } };
export const readTailorProfile: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: { profile: await getTailorProfile(request.auth!.userId) } }); } catch (error) { next(error); } };
export const patchTailorProfile: RequestHandler = async (request, response, next) => { try { response.json({ success: true, data: { profile: await updateTailorProfile(request.auth!.userId, tailorProfileSchema.parse(request.body)) } }); } catch (error) { next(error); } };
export const addTailorVerification: RequestHandler = async (request, response, next) => { try { response.status(201).json({ success: true, data: { verification: await submitTailorVerification(request.auth!.userId, tailorVerificationSchema.parse(request.body)) } }); } catch (error) { next(error); } };
